// THROWAWAY PROTOTYPE — ticket #35. Generator driver.
// Reads operations/*.graphql, emits generated/<Name>.<fallback>.ts

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { buildClientSchema, Kind, parse, validate } from "graphql";
import { emitOperation, type Fallback, transformDocument } from "./emit.ts";
import { SchemaIndex } from "./schema-index.ts";

const here = new URL("..", import.meta.url).pathname;
const introspection = JSON.parse(
	readFileSync(join(here, "fixtures/mockshop.introspection.json"), "utf8"),
);
const idx = new SchemaIndex(introspection);
const clientSchema = buildClientSchema(introspection.data);

const FALLBACKS: Fallback[] = ["expand", "catchall"];

const files = readdirSync(join(here, "operations")).filter((f) =>
	f.endsWith(".graphql"),
);

const report: Array<Record<string, unknown>> = [];

for (const file of files) {
	const src = readFileSync(join(here, "operations", file), "utf8");
	const doc = parse(src);

	// Sanity: the document must be valid against the real schema, or the probe
	// is measuring a typo instead of a design.
	const errors = validate(clientSchema, doc);
	if (errors.length > 0) {
		console.error(
			`✗ ${file} INVALID: ${errors.map((e) => e.message).join("; ")}`,
		);
		continue;
	}

	for (const def of doc.definitions) {
		if (def.kind !== Kind.OPERATION_DEFINITION) continue;
		const name = def.name?.value ?? basename(file, ".graphql");

		for (const fallback of FALLBACKS) {
			const { expr, stats } = emitOperation(idx, doc, def, {
				fallback,
				taggedUnion: true,
			});
			const transformed = transformDocument(idx, doc, def);
			const out = `// GENERATED by the #35 prototype — do not edit, do not ship.
import { Schema } from "effect";

export const document = ${JSON.stringify(transformed)};

export const ${name}Schema = ${expr};

export type ${name}Result = typeof ${name}Schema.Type;
export type ${name}Encoded = typeof ${name}Schema.Encoded;
`;
			const outFile = `${name}.${fallback}.ts`;
			writeFileSync(join(here, "generated", outFile), out);

			if (fallback === "expand") {
				report.push({
					operation: name,
					depth: stats.maxDepth,
					structs: stats.structs,
					unions: stats.unions,
					members: stats.unionMembers.join("/") || "-",
					optionalKeys: stats.optionalKeys,
					deferred: stats.deferredFragments,
					typenameInjected: stats.typenameInjections,
					bytes: out.length,
				});
			}
		}
	}
}

console.log("\n=== generated (fallback=expand) ===");
console.table(report);

// catchall sizes, for the arity comparison
const sizes = readdirSync(join(here, "generated")).map((f) => ({
	file: f,
	bytes: readFileSync(join(here, "generated", f), "utf8").length,
}));
console.log("\n=== emitted sizes ===");
console.table(sizes.sort((a, b) => b.bytes - a.bytes).slice(0, 10));
